table dTipoVariacao
	lineageTag: 4405fcea-1a93-436c-9424-445771074d4d

	column Tipo
		dataType: string
		lineageTag: b9d21a56-3538-4894-98d2-d0c7dc7458b9
		summarizeBy: none
		sourceColumn: Tipo

		annotation SummarizationSetBy = Automatic

	column 'Tipo Viz'
		dataType: string
		lineageTag: 1cb574a6-e4ac-443e-9d09-0f5d80aff10c
		summarizeBy: none
		sourceColumn: Tipo Viz

		annotation SummarizationSetBy = Automatic

	partition dTipoVariacao = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W8j28qljBMa8ktSgzv0hJB8xXitWJVnLMy0cWB3KVYmMB", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Tipo = _t, #"Tipo Viz" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Tipo", type text}, {"Tipo Viz", type text}})
				in
				    #"Tipo Alterado"

	changedProperty = Name

	annotation PBI_ResultType = Table

